/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeee;

import javax.swing.DefaultListModel;

/**
 *
 * @author FalaZezeBomDiaCara
 */
public class ProjetoTeste extends javax.swing.JFrame {
DefaultListModel lista = new DefaultListModel();
    /**
     * Creates new form ProjetoTeste
     */
    public ProjetoTeste() {
        initComponents();
        pncRes.setVisible(false);
        
        lista.addElement("Ola");
        lista.addElement("Filho");
        lista.addElement("da");
        lista.addElement("Puta");
        lstR.setModel(lista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sliUm = new javax.swing.JSlider();
        sliDois = new javax.swing.JSlider();
        lblUm = new javax.swing.JLabel();
        lblDois = new javax.swing.JLabel();
        pncRes = new javax.swing.JPanel();
        lblResN1x = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblResN2x = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResN1m = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblResN2m = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblResx = new javax.swing.JLabel();
        lblResm = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstR = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Número 1");

        jLabel2.setText("Número 2");

        sliUm.setValue(0);
        sliUm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliUmStateChanged(evt);
            }
        });

        sliDois.setValue(0);
        sliDois.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliDoisStateChanged(evt);
            }
        });

        lblUm.setText("0");

        lblDois.setText("0");

        pncRes.setBackground(new java.awt.Color(255, 255, 255));
        pncRes.setForeground(new java.awt.Color(0, 0, 204));

        lblResN1x.setForeground(new java.awt.Color(0, 0, 204));
        lblResN1x.setText("0");

        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("x");

        lblResN2x.setForeground(new java.awt.Color(0, 0, 204));
        lblResN2x.setText("0");

        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("=");

        lblResN1m.setForeground(new java.awt.Color(0, 0, 204));
        lblResN1m.setText("0");

        jLabel8.setForeground(new java.awt.Color(153, 0, 153));
        jLabel8.setText("+");

        lblResN2m.setForeground(new java.awt.Color(0, 0, 204));
        lblResN2m.setText("0");

        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("=");

        lblResx.setForeground(new java.awt.Color(204, 0, 0));
        lblResx.setText("0");

        lblResm.setForeground(new java.awt.Color(204, 0, 0));
        lblResm.setText("0");

        javax.swing.GroupLayout pncResLayout = new javax.swing.GroupLayout(pncRes);
        pncRes.setLayout(pncResLayout);
        pncResLayout.setHorizontalGroup(
            pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncResLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResN1m, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(lblResN1x, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pncResLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResN2x, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pncResLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblResN2m, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pncResLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResx, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(lblResm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pncResLayout.setVerticalGroup(
            pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pncResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResN1x)
                    .addComponent(jLabel4)
                    .addComponent(lblResN2x)
                    .addComponent(jLabel6)
                    .addComponent(lblResx))
                .addGap(18, 18, 18)
                .addGroup(pncResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResN1m)
                    .addComponent(jLabel8)
                    .addComponent(lblResN2m)
                    .addComponent(jLabel10)
                    .addComponent(lblResm))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(lstR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUm))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDois)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pncRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(sliUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUm))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(sliDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDois))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(pncRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliUmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliUmStateChanged
        // TODO add your handling code here:
        pncRes.setVisible(true);
        int n1 = sliUm.getValue();
        int m;
        int x = 1;
        lblUm.setText(Integer.toString(n1));
        lblResN1x.setText(Integer.toString(n1));
        lblResN1m.setText(Integer.toString(n1));
        m = sliUm.getValue() + sliDois.getValue();
        lblResm.setText(Integer.toString(m));
        x = sliUm.getValue() * sliDois.getValue();
        lblResx.setText(Integer.toString(x));
        lista.removeAllElements();
    }//GEN-LAST:event_sliUmStateChanged

    private void sliDoisStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliDoisStateChanged
        // TODO add your handling code here:
        pncRes.setVisible(true);
        int n2 = sliDois.getValue();
        int m;
        int x;
        lblDois.setText(Integer.toString(n2));
        lblResN2x.setText(Integer.toString(n2));
        lblResN2m.setText(Integer.toString(n2));
        m = sliUm.getValue() + sliDois.getValue();
        lblResm.setText(Integer.toString(m));
        x = sliUm.getValue() * sliDois.getValue();
        lblResx.setText(Integer.toString(x));
        lista.removeAllElements();
    }//GEN-LAST:event_sliDoisStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDois;
    private javax.swing.JLabel lblResN1m;
    private javax.swing.JLabel lblResN1x;
    private javax.swing.JLabel lblResN2m;
    private javax.swing.JLabel lblResN2x;
    private javax.swing.JLabel lblResm;
    private javax.swing.JLabel lblResx;
    private javax.swing.JLabel lblUm;
    private javax.swing.JList lstR;
    private javax.swing.JPanel pncRes;
    private javax.swing.JSlider sliDois;
    private javax.swing.JSlider sliUm;
    // End of variables declaration//GEN-END:variables
}
